algoritmo "exemplo 1"

var
    n1: inteiro;
    n2: inteiro;
    n3: inteiro;
    n4: inteiro;
    soma: inteiro;
inicio

 n1 <- 7
 n2 <- 5
 n3 <- 3
 n4 <- 2
 soma <- n1 + n2 + n3 + n4

  escreval("O número", n1, " é primo")
  escreval("O número", n2, " é primo")
  escreval("O número", n3, " é primo")
  escreval("O número", n4, " é primo")
  escreval("A soma de todos os números primos menores iguais a", n1, " é:", soma)

fimalgoritmo